def get_company_name(company_number):
    company_dict = {
1 : "Anonymous",
2 : "RBC Capital Markets",
3 : "ATB Securities Inc",
4 : "Cantor Fitzgerald Canada Corporation",
5 : "Citadel Securities Canada ULC",
6 : "INFOR Financial Inc.",
7 : "TD Securities Inc.",
8 : "Eight Capital",
9 : "BMO Nesbitt Burns Inc.",
10 : "StephenAvenue Securities Inc.",
13 : "Instinet Canada Ltd.",
14 : "Virtu Canada Corp.",
15 : "UBS Securities Canada Inc./UBS Valeurs Mobilieres Canada Inc.",
16 : "Paradigm Capital Inc.",
17 : "Integral Wealth Securities Limited",
18 : "Echelon Wealth Partners Inc.",
19 : "Desjardins Securities Inc.",
21 : "PGM Global Inc.",
22 : "Fidelity Clearing Canada ULC",
23 : "State Street Global Markets Canada Inc.",
24 : "Clarus Securities Inc",
25 : "Odlum Brown Ltd.",
26 : "Wells Fargo Securities Canada Ltd.",
28 : "CI Investment Services Inc. ",
33 : "Canaccord Genuity Corp.",
34 : "Maison Placements Canada Inc.",
35 : "Friedberg Mercantile Group",
36 : "W.D. Latimer Co. Ltd.",
38 : "Liquidnet Canada Inc",
39 : "Merrill Lynch Canada Inc.",
43 : "Caldwell Securities Ltd.",
48 : "Laurentian Bank Securities Inc.",
53 : "Morgan Stanley Canada Ltd.",
55 : "Velocity Trade Capital Ltd.",
56 : "Edward Jones",
57 : "Interactive Brokers Canada Inc",
59 : "PI Financial Corp.",
62 : "Haywood Securities Inc.",
65 : "Goldman Sachs Canada Inc.",
68 : "Leede Jones Gable Inc.",
70 : "Manulife Securities Incorporated",
72 : "Credit Suisse Securities (Canada), Inc.",
73 : "Cormark Securities Inc./Valeurs Mobilieres Cormark Inc.",
76 : "iA Private Wealth Inc.",
77 : "Peters & Co. Ltd.",
79 : "CIBC World Markets  Inc.",
80 : "National Bank Financial Inc.",
81 : "HSBC Securities (Canada) Inc.",
82 : "Stifel Nicolaus Canada Inc.",
83 : "Research Capital Corporation",
84 : "Independent Trading Group",
85 : "Scotia Capital Inc.",
86 : "Pictet Canada L.P.",
87 : "Beacon Securities Ltd.",
88 : "Credential Qtrade Securities Inc.",
89 : "Raymond James Ltd.",
90 : "Barclays Capital Canada Inc.",
91 : "JonesTrading Canada Inc.",
92 : "Pollitt & Co. Inc.",
94 : "Hampton Securities Ltd.",
98 : "Red Cloud Securites Inc.",
100 : "TSX Buy-ins",
101 : "Societe Generale Capital Canada Inc.",
123 : "Citigroup Global Markets Canada",
124 : "Questrade Inc.",
150 : "Generation IACP Inc.",
200 : "Acumen Capital Finance Partners Ltd.",
201 : "Wellington-Altus Private Wealth Inc.",
203 : "Assante Capital Management Ltd.",
205 : "Lightyear Capital Inc.",
207 : "Gravitas Securities Inc.",
208 : "Kingwest and Company",
218 : "Emerging Equities Inc",
222 : "JP Morgan Securities Canada Inc.",
300 : "CSE Buy-ins",
301 : "NEO Buy-ins",

    }
    
    return company_dict.get(company_number, "Unknown Company")